version: "2.2"
services:
  jav:
    image: jav:local
    build: .
    volumes:
      - ./config.ini:/jav/config.ini
      - ./downloads/complete:/jav/data
    command:
      - python
      - /jav/AV_Data_Capture.py
      - -a
